### Get all acitivity
GET localhost:5000/api/activities

### Get activity by id
GET localhost:5000/api/activities/7aee3ae2-310b-44e2-b3ad-23bfa8d4a0b0

### Create activity
POST localhost:5000/api/activities
Content-Type: application/json

{
  "title": "Morning learning session",
  "description": "Wrap up the CRUD part of Reactivities project",
  "category": "Learning",
  "date": "2022-10-10T11:22:42.9822309",
  "city": "Houston",
  "venue": "Thao's estates"
}

### Update activity
PUT localhost:5000/api/activities/0a3080bb-b513-434b-b58e-076f6e5990f4
Content-Type: application/json

{
  "description": "Wrap up the CRUD part of Reactivities project",
  "category": "Learning",
  "date": "2022-10-10T11:22:42.9822309",
  "city": "Houston",
  "venue": "Thao's estates"
}

### Delete activity
DELETE localhost:5000/api/activities/4db4a9f3-5047-47f1-90a5-2b30cfb6c6e0