### Get all acitivity
GET localhost:5000/api/activities

### Get activity by id
GET localhost:5000/api/activities/7aee3ae2-310b-44e2-b3ad-23bfa8d4a0b0

### Create activity
POST localhost:5000/api/activities
Content-Type: application/json

{
  "description": ".NET Core development best practices, C# and clean architecture!",
  "category": "Learning",
  "date": "2022-09-18T07:22:42.9822309",
  "city": "Houston",
  "venue": "Thao's estates"
}

### Update activity
PUT localhost:5000/api/activities/4db4a9f3-5047-47f1-90a5-2b30cfb6c6e0
Content-Type: application/json

{
  "title": "Working at the office",
  "description": "Real Time Power!"
}

### Delete activity
DELETE localhost:5000/api/activities/b2a29d53-b4e3-4598-b3e1-2f410cb54477