// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("Domain.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d4917ce1-0cc9-49ec-b7f9-9bace564d130"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2022, 7, 16, 5, 22, 42, 982, DateTimeKind.Local).AddTicks(2108),
                            Description = "Activity 2 months ago",
                            Title = "Past Activity 1",
                            Venue = "Pub"
                        },
                        new
                        {
                            Id = new Guid("99df3931-32e9-48bd-9fdd-07afce405b84"),
                            Category = "culture",
                            City = "Paris",
                            Date = new DateTime(2022, 8, 16, 5, 22, 42, 982, DateTimeKind.Local).AddTicks(2170),
                            Description = "Activity 1 month ago",
                            Title = "Past Activity 2",
                            Venue = "Louvre"
                        },
                        new
                        {
                            Id = new Guid("9e902e71-8f19-4993-ba8a-7288559bbf48"),
                            Category = "culture",
                            City = "London",
                            Date = new DateTime(2022, 10, 16, 5, 22, 42, 982, DateTimeKind.Local).AddTicks(2193),
                            Description = "Activity 1 month in future",
                            Title = "Future Activity 1",
                            Venue = "Natural History Museum"
                        },
                        new
                        {
                            Id = new Guid("c79bb016-6d7c-4983-87f7-6c5e5062d9d2"),
                            Category = "music",
                            City = "London",
                            Date = new DateTime(2022, 11, 16, 5, 22, 42, 982, DateTimeKind.Local).AddTicks(2217),
                            Description = "Activity 2 months in future",
                            Title = "Future Activity 2",
                            Venue = "O2 Arena"
                        },
                        new
                        {
                            Id = new Guid("f02d651a-304c-402e-9cd1-ad2c70d7481b"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2022, 12, 16, 5, 22, 42, 982, DateTimeKind.Local).AddTicks(2242),
                            Description = "Activity 3 months in future",
                            Title = "Future Activity 3",
                            Venue = "Another pub"
                        },
                        new
                        {
                            Id = new Guid("8ef4aa56-87b1-4dcd-a683-bd933c5082a1"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2023, 1, 16, 5, 22, 42, 982, DateTimeKind.Local).AddTicks(2264),
                            Description = "Activity 4 months in future",
                            Title = "Future Activity 4",
                            Venue = "Yet another pub"
                        },
                        new
                        {
                            Id = new Guid("b2a29d53-b4e3-4598-b3e1-2f410cb54477"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2023, 2, 16, 5, 22, 42, 982, DateTimeKind.Local).AddTicks(2286),
                            Description = "Activity 5 months in future",
                            Title = "Future Activity 5",
                            Venue = "Just another pub"
                        },
                        new
                        {
                            Id = new Guid("8bd0a1f8-f0ab-4323-9c57-7b6174fb0683"),
                            Category = "music",
                            City = "London",
                            Date = new DateTime(2023, 3, 16, 5, 22, 42, 982, DateTimeKind.Local).AddTicks(2309),
                            Description = "Activity 6 months in future",
                            Title = "Future Activity 6",
                            Venue = "Roundhouse Camden"
                        },
                        new
                        {
                            Id = new Guid("7aee3ae2-310b-44e2-b3ad-23bfa8d4a0b0"),
                            Category = "travel",
                            City = "London",
                            Date = new DateTime(2023, 4, 16, 5, 22, 42, 982, DateTimeKind.Local).AddTicks(2331),
                            Description = "Activity 2 months ago",
                            Title = "Future Activity 7",
                            Venue = "Somewhere on the Thames"
                        },
                        new
                        {
                            Id = new Guid("99d8fe9c-94b8-4d80-bbfd-4bccc496d54f"),
                            Category = "film",
                            City = "London",
                            Date = new DateTime(2023, 5, 16, 5, 22, 42, 982, DateTimeKind.Local).AddTicks(2353),
                            Description = "Activity 8 months in future",
                            Title = "Future Activity 8",
                            Venue = "Cinema"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
